# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hayq/Desktop/ChessQK-lv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hayq/Desktop/Build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hayq/Desktop/Build/CMakeFiles /home/hayq/Desktop/Build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hayq/Desktop/Build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QK

# Build rule for target.
QK: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QK
.PHONY : QK

# fast build rule for target.
QK/fast:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/build
.PHONY : QK/fast

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Board.cpp.s
.PHONY : Board.cpp.s

Figure.o: Figure.cpp.o

.PHONY : Figure.o

# target to build an object file
Figure.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Figure.cpp.o
.PHONY : Figure.cpp.o

Figure.i: Figure.cpp.i

.PHONY : Figure.i

# target to preprocess a source file
Figure.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Figure.cpp.i
.PHONY : Figure.cpp.i

Figure.s: Figure.cpp.s

.PHONY : Figure.s

# target to generate assembly for a file
Figure.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Figure.cpp.s
.PHONY : Figure.cpp.s

Knight.o: Knight.cpp.o

.PHONY : Knight.o

# target to build an object file
Knight.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Knight.cpp.o
.PHONY : Knight.cpp.o

Knight.i: Knight.cpp.i

.PHONY : Knight.i

# target to preprocess a source file
Knight.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Knight.cpp.i
.PHONY : Knight.cpp.i

Knight.s: Knight.cpp.s

.PHONY : Knight.s

# target to generate assembly for a file
Knight.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Knight.cpp.s
.PHONY : Knight.cpp.s

Main.o: Main.cpp.o

.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Main.cpp.s
.PHONY : Main.cpp.s

Position.o: Position.cpp.o

.PHONY : Position.o

# target to build an object file
Position.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Position.cpp.o
.PHONY : Position.cpp.o

Position.i: Position.cpp.i

.PHONY : Position.i

# target to preprocess a source file
Position.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Position.cpp.i
.PHONY : Position.cpp.i

Position.s: Position.cpp.s

.PHONY : Position.s

# target to generate assembly for a file
Position.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Position.cpp.s
.PHONY : Position.cpp.s

Queen.o: Queen.cpp.o

.PHONY : Queen.o

# target to build an object file
Queen.cpp.o:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Queen.cpp.o
.PHONY : Queen.cpp.o

Queen.i: Queen.cpp.i

.PHONY : Queen.i

# target to preprocess a source file
Queen.cpp.i:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Queen.cpp.i
.PHONY : Queen.cpp.i

Queen.s: Queen.cpp.s

.PHONY : Queen.s

# target to generate assembly for a file
Queen.cpp.s:
	$(MAKE) -f CMakeFiles/QK.dir/build.make CMakeFiles/QK.dir/Queen.cpp.s
.PHONY : Queen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... QK"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... Figure.o"
	@echo "... Figure.i"
	@echo "... Figure.s"
	@echo "... Knight.o"
	@echo "... Knight.i"
	@echo "... Knight.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Position.o"
	@echo "... Position.i"
	@echo "... Position.s"
	@echo "... Queen.o"
	@echo "... Queen.i"
	@echo "... Queen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

